### ISSUE TITLE
Problem in integrating API in my website

### ISSUE THREAD

**Issue by jayendra48** [Ixolit/php-ixopay#4]
I could not find the whether to put credit card details. every method is shown without using credit cards.
I could not find option to connect with adapters.
please tell me how can i connect to an adapter

**Comment by marcod85** [comment]
Hi,

please refer to the official IXOPAY documentation on https://gateway.ixopay.com/documentation

If your system is PCI compliant, please contact your integration engineer for further documentation about the Direct API. This repo here on GitHub is only for the non-PCI API.

You will get API Key and other credentials necessary to send transaction to a connector provided by your integration engineer, or in case you are an Enterprise Merchant have to set up the appropriate connectors within the Admin panel.
